local_test_package <- function(env = parent.frame()) {
  pkg <- withr::local_tempdir(.local_envir = env)

  writeLines(
    c(
      "Package: testpkg",
      "Title: Test Package",
      "Version: 0.0.0.9000",
      paste0(
        "Authors@R: person('A', 'Tester', ",
        "email = 'a@example.com', role = c('aut', 'cre'))"
      ),
      "Description: A small package fixture for tests.",
      "License: MIT",
      "Encoding: UTF-8"
    ),
    file.path(pkg, "DESCRIPTION")
  )

  dir.create(file.path(pkg, "R"))
  writeLines("# Generated by test fixture", file.path(pkg, "NAMESPACE"))

  pkg
}

local_test_project <- function(env = parent.frame()) {
  pkg <- local_test_package(env = env)
  usethis::local_project(
    path = pkg,
    force = TRUE,
    quiet = TRUE,
    .local_envir = env
  )

  pkg
}

write_rd <- function(pkg, name, lines) {
  man <- file.path(pkg, "man")
  dir.create(man, showWarnings = FALSE)

  path <- file.path(man, paste0(name, ".Rd"))
  writeLines(lines, path)
  path
}
