on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: test

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          
      # This is needed for workflows running on
      # ubuntu-20.04 or later
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 3
          extra-packages: |
            pkgdown
          needs: website

      - name: Update docs
        run: |
          
          getOption("repos")
          message(getOption("repos"))

        shell: Rscript {0}


