name: Clear all Github actions caches manually
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 1,3,5'

jobs:
  cache-clear:
    runs-on: ubuntu-latest

    steps:
      - uses: easimon/wipe-cache@main

